# Generated by Django 6.0.5 on 2026-05-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnezRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list)),
                ('detected_category', models.CharField(blank=True, max_length=50)),
                ('risk_detected', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnez_records', to='core.patient')),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnez_record', to='core.queueentry')),
            ],
            options={
                'verbose_name': 'Anamnez Kaydı',
                'verbose_name_plural': 'Anamnez Kayıtları',
            },
        ),
    ]
